---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
        # Fail if committing to master
        # Fail if committing to branch that does not follow one of these patterns:
        # feature/TICKET-123/description
        # bugfix/TICKET-123/description
        # docs/TICKET-123/description
      - id: no-commit-to-branch
        language_version: python3.7
        args:
          - --branch=master
          - --pattern=^(?!(feature|bugfix|docs)\/[A-Z]+-\d+\/\w+).*
        stages:
          - commit
          - push

        # Modify in place then fail
        # Ensure file ends in blank line
      - id: end-of-file-fixer
        language_version: python3.7
        stages:
          - commit
          - push

        #  Modify in place then fail
        # Ensure lines have no trailing whitespace
      - id: trailing-whitespace
        language_version: python3.7
        args:
          - --markdown-linebreak-ext=md
        stages:
          - commit
          - push

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:

        #  Modify in place then fail
        #  Determine imports for "isort" hook
      - id: seed-isort-config
        language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:

      #  Modify in place then fail
      #  Sort Python imports  using config in 'tox.ini'
      - id: isort
        language_version: python3.7
        stages:
          - commit
          - push

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:

      #  Modify in place then fail
      #  Apply 'black' autoformatter to Python files
      - id: black
        language_version: python3.7
        args:
          - --line-length=120
        stages:
          - commit
          - push

  - repo: https://github.com/bemeurer/beautysh
    rev: 6.0.1
    hooks:

      #  Modify in place then fail
      #  Apply 'beautysh' autoformatter to Bash files
      - id: beautysh
        language_version: python3.7
        stages:
          - commit
          - push

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:

      #  Lint then fail
      #  Validate Python docstrings with 'pydocstyle' using config in 'tox.ini'
      - id: pydocstyle
        language_version: python3.7
        stages:
          - commit
          - push
        exclude: tests/*

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:

      #  Lint then fail
      #  Check for BOM
      - id: check-byte-order-marker
        language_version: python3.7
        stages:
          - commit
          - push

  - repo: local
    hooks:
      # Lint then fail
      # Validate Python files with 'flake8' using config in 'tox.ini'
      - id: wemake
        name: wemake
        description: wemake-python-styleguide encforcement
        entry: flake8
        language: python
        language_version: python3.7
        args:
          - --config=tox.ini
        stages:
          - commit
          - push
        types:
          - python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:

      # Lint then fail
      # Validate Python files with 'mypy' using config in 'tox.ini'
      - id: mypy
        language_version: python3.7
        stages:
          - commit
          - push

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.11  # or specific tag
    hooks:
      #  Modify in place then fail
      #  Apply 'yamlfmt' autoformatter to yaml files
      - id: yamlfmt
        args:
          - --width=120
          - --mapping=2
          - --sequence=4
          - --offset=2

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.20.0
    hooks:

      # Lint then fail
      # Validate Yaml files
      - id: yamllint
        args:
          - '-d {extends: relaxed, rules: {line-length: {max: 120}}}'
        stages:
          - commit
          - push

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:

      # Lint then fail
      # Validate Dockerfiles
      - id: dockerfilelint
        stages:
          - commit
          - push

  - repo: https://github.com/openstack/bashate
    rev: 2.0.0
    hooks:

      #  Lint then fail
      #  Apply 'bashate' autoformatter to Bash files
      - id: bashate
        language_version: python3.7
        args:
          - --ignore=E006
        stages:
          - commit
          - push
        verbose: false

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      # Lint then fail
      # Apply 'shellcheck' linter to shell scripts
      - id: shellcheck
        language_version: python3.7
        stages:
          - commit
          - push

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      #  Lint then fail
      #  Apply 'bandit' security check
      - id: bandit
        language_version: python3.7
        args:
          - --exclude=tests/*
        stages:
          - commit
          - push
