---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: default
      image: registry.ucp.cxmgmtawsprd.massmutual.com/datascience/manylinux2010_x86_64:0.5.0
      command:
        - cat
      tty: true
